# Generated by Django 3.2.15 on 2022-09-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthestoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_description',
            field=models.CharField(default='placeholder', max_length=200),
            preserve_default=False,
        ),
    ]
