# Generated by Django 3.2.15 on 2022-09-12 09:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('synthestoryapp', '0006_auto_20220912_0912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoryIdeas',
            new_name='StoryIdea',
        ),
    ]
