# Generated by Django 3.2.15 on 2022-09-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synthestoryapp', '0007_rename_storyideas_storyidea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyidea',
            name='slug',
        ),
    ]
