# Generated by Django 3.2.15 on 2022-09-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synthestoryapp', '0008_remove_storyidea_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyidea',
            options={'ordering': ['updated_on']},
        ),
    ]
