# Generated by Django 3.2.15 on 2022-09-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synthestoryapp', '0009_alter_storyidea_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyidea',
            options={'ordering': ['-updated_on']},
        ),
    ]
