# Generated by Django 3.2.15 on 2022-09-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthestoryapp', '0010_alter_storyidea_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyidea',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
